apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bgd-helm
spec:
  destination:
    namespace: user%USERNUM%-bgdh
    server: 'https://kubernetes.default.svc'
  source:
    path: documentation/modules/ROOT/examples/bgd-helm-chart
    repoURL: 'https://gitlab.com/gitlab-partners-public/red-hat-demos/jay-howell-openshift-gitops-workshop'
    targetRevision: master
    helm:
      valueFiles:
        - custom_values_1/values.yaml
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
